site_name: wspr-ai-lite
site_url: https://KI7MT.github.io/wspr-ai-lite/
repo_url: https://github.com/KI7MT/wspr-ai-lite
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Quickstart: userguide/quick-start.md
  - User Guide:
      - Overview: userguide/user-guide.md
      - User Interface: userinterface/ui.md
      - CLI Reference:
          - Ingest: userguide/cli/ingest.md
          # - Fetch: cli/fetch.md                 # optional future page
          # - Tools: cli/tools.md                 # optional future page
          # - MCP Server: cli/tools.md                 # optional future page

  - Data Reference:
      - Schema: development/schema.md

  - Development:
      - Dev Setup: development/developer-setup.md
      - Makefile: development/makefile.md
      - Testing: development/testing.md
      - Release Process: development/process-release.md
      - Troubleshooting: development/troubleshooting.md

  - Project:
      - Roadmap: ROADMAP.md
      - Contributors: CONTRIBUTORS.md
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Security: SECURITY.md
      - License (download): LICENSE

  - Support: SUPPORT.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  version: !ENV [WSPR_AI_LITE_VERSION, dev]

plugins:
  - search

# MkDocs serves content from the ./docs directory.
# Make sure these files exist (copied from your repo):
#   docs/README.md, docs/DEV_SETUP.md, docs/MAKEFILE.md, docs/TESTING.md, docs/TROUBLESHOOTING.md
