site_name: wspr-ai-lite
site_url: https://KI7MT.github.io/wspr-ai-lite/
repo_url: https://github.com/KI7MT/wspr-ai-lite
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md  # maps docs/README.md to site index
  - Quickstart: ingest.md
  - User Setup: user-setup.md
  - User Interface: ui.md
  - Development:
    - Dev Setup: developer-setup.md
    - Makefile: makefile.md
    - Testing: testing.md
    - Process Release: process-release.md
    - Troubleshooting: troubleshooting.md
  - Schema: schema.md
  - Project:
    - Roadmap: ROADMAP.md
    - Contributors:  CONTRIBUTORS.md
    - Contributing: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Security: SECURITY.md
    - License: LICENSE
    - Security: SECURITY.md
  - Support: SUPPORT.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  version: !ENV [WSPR_AI_LITE_VERSION, dev]

plugins:
  - search

# MkDocs serves content from the ./docs directory.
# Make sure these files exist (copied from your repo):
#   docs/README.md, docs/DEV_SETUP.md, docs/MAKEFILE.md, docs/TESTING.md, docs/TROUBLESHOOTING.md
