name: publish
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      # Optional safety check: tag == pyproject version
      - name: Verify tag matches package version
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF_NAME#v}"
          echo "Tag: $TAG"
          PYPROJ_VERSION=$(python -c "import tomllib, pathlib; print(tomllib.loads(pathlib.Path('pyproject.toml').read_text(encoding='utf-8'))['project']['version'])")
          echo "Version in pyproject.toml: $PYPROJ_VERSION"
          [ -n "$PYPROJ_VERSION" ] || { echo "Could not read version"; exit 1; }
          test "$TAG" = "$PYPROJ_VERSION" || { echo "Tag $TAG != pyproject $PYPROJ_VERSION"; exit 1; }

      - name: Build wheel+sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true

  github-release:
    needs: build-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create GitHub Release (auto notes) and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*
          # mark pre-releases automatically if tag contains -rc or -beta, etc.
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
