name: docs

on:
  push:
    branches: [ main ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'src/**'          # rebuild if you show version from code (macros)
      - '.github/workflows/docs.yml'
  workflow_dispatch: {}   # allow manual rebuilds from Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-material-extensions mkdocs-macros-plugin

      - name: Build site
        run: mkdocs build --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
